[package]
name = "pingo"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
rand = "0.9.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "std"] }
